apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      #fsGroup: 65532
      runAsUser: 0
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params:
    - name: repo-url
      value: https://github.com/noumanxgrid/kube-front  # Replace with your Git repo URL
    - name: image-reference
      value: n0man2ahmed/tektoncicd:v1  # Replace with your Docker image reference

