apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appbackend
  template:
    metadata:
      labels:
        app: appbackend
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m03
      containers:
        - name: backend-container
          image: n0man2ahmed/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgres-password
            - name: POSTGRES_ENDPOINT
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: postgres-user
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: appbackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

